package com.sword.trailersdb.data.dtos.comment;

public class PostCommentDto {

    private String text;
    private Long rating;
    private Long user_id;
    // private Date datePosted;     TODO: Delete. It must be autogenerated.
    // private Movie movie_id;      TODO: Finish movie integration.

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Long getRating() {
        return rating;
    }

    public void setRating(Long rating) {
        this.rating = rating;
    }

    public Long getUser_id() {
        return user_id;
    }

    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }
}